name: Update Riven Data

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 2'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Check out repo
        uses: actions/checkout@v3
      - name: ğŸ¦• Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: ğŸšš Fetch PC data 
        uses: githubocto/flat@v3
        with:
          http_url: http://n9e5v4d8.ssl.hwcdn.net/repos/weeklyRivensPC.json
          downloaded_filename: pc.json
      - name: ğŸšš Fetch Switch data 
        uses: githubocto/flat@v3
        with:
          http_url: http://n9e5v4d8.ssl.hwcdn.net/repos/weeklyRivensSWI.json
          downloaded_filename: swi.json
      - name: ğŸšš Fetch Xbox data 
        uses: githubocto/flat@v3
        with:
          http_url: http://n9e5v4d8.ssl.hwcdn.net/repos/weeklyRivensXB1.json
          downloaded_filename: xb1.json
      - name: ğŸšš Fetch PS4 data 
        uses: githubocto/flat@v3
        with:
          http_url: http://n9e5v4d8.ssl.hwcdn.net/repos/weeklyRivensPS4.json
          downloaded_filename: ps4.json
